apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: bff-service-deployment
  labels:
    app: bff-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bff-service
  template:
    metadata:
      labels:
        app: bff-service
    spec:
      containers:
      - name: bff-service
        image: aiweaver/bff-service:2.0
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: k8s
        resources:
          requests:
            memory: "256Mi"
            cpu: "0.25"
          limits:
            memory: "1Gi"
            cpu: "0.5"
         # readinessProbe: 
         #  httpGet:
         #    path: /v1/promotions
         #    port: 8080
         #  initialDelaySeconds: 30 
         #  periodSeconds: 10 
         #livenessProbe: 
         #  exec:
         #    command:
         #    - cat
         #    - bff-service
         #  initialDelaySeconds: 60
         #  periodSeconds: 5
