apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: recommendation-service-deployment
  labels:
    app: recommendation-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommendation-service
  template:
    metadata:
      labels:
        app: recommendation-service
        version: v1
    spec:
      containers:
      - name: recommendation-service
        image: aiweaver/recommendation-service:1.0
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: k8s
        resources:
          requests:
            memory: "256Mi"
            cpu: "0.25"
          limits:
            memory: "1Gi"
            cpu: "0.5"
