apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: recommendation-service
spec:
  host: recommendation-service
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: recommendation-service
spec:
  hosts:
  - recommendation-service
  http:
  - route: 
    - destination:
        host: recommendation-service
        subset: v1
      weight: 10
    - destination:
        host: recommendation-service
        subset: v2
      weight: 90
    fault:
      abort:
        httpStatus: 500
        percent: 100